const KEY='roadHeroData';
const AUTH={email:'admin@roadhhero.local',password:'RoadHero@2026'};
const seed={riders:[{id:'R-001',name:'Ahmed Khan',vehicle:'Toyota Corolla 2022',team:'Lahore',deliveries:124,success:96,attendance:98,kpi:94,status:'Active'},{id:'R-002',name:'Sarah Jenkins',vehicle:'Honda City 2021',team:'Lahore',deliveries:118,success:95,attendance:97,kpi:93,status:'Active'},{id:'R-003',name:'Marcus Torres',vehicle:'Suzuki Bolan 2019',team:'Central',deliveries:102,success:91,attendance:94,kpi:88,status:'Active'},{id:'R-004',name:'David Chen',vehicle:'',team:'Central',deliveries:88,success:89,attendance:92,kpi:85,status:'Active'},{id:'R-005',name:'Usman Ali',vehicle:'',team:'Lahore',deliveries:76,success:87,attendance:90,kpi:82,status:'On Leave'}],vehicles:[{id:'V-001',name:'Toyota Corolla 2022',registration:'RH-2022-01',status:'Active',mileage:42000},{id:'V-002',name:'Honda City 2021',registration:'RH-2021-02',status:'Active',mileage:51000},{id:'V-003',name:'Suzuki Bolan 2019',registration:'RH-2019-03',status:'Maintenance',mileage:73000}],deliveries:[],maintenance:[],inspections:[],fuel:[],incidents:[],training:[],attendance:[],documents:[],assignments:[],alerts:[]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||seed;let page='dashboard';let editing=null;
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(v=''){return String(v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]))}
function calc(){const r=data.riders,v=data.vehicles,d=data.deliveries;return{riders:r.length,vehicles:v.length,deliveries:d.length||r.reduce((a,x)=>a+x.deliveries,0),success:r.length?Math.round(r.reduce((a,x)=>a+x.success,0)/r.length):0,active:v.filter(x=>x.status==='Active').length}}
function render(){document.getElementById('app').innerHTML=page==='login'?login():shell();if(page==='login')return;renderPage();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function login(){return `<main class="login"><form class="login-card" onsubmit="doLogin(event)"><div class="logo">ROAD HERO</div><p class="muted">Fleet Management Portal</p><label class="field">Email<input id="email" type="email" required value="admin@roadhhero.local"></label><label class="field">Password<input id="password" type="password" required></label><label><input id="remember" type="checkbox"> Remember me</label><button class="primary" type="submit">Sign in</button><p class="muted">Offline local administrator access</p></form></main>`}
function doLogin(e){e.preventDefault();if(email.value===AUTH.email&&password.value===AUTH.password){sessionStorage.setItem('rhAuth','1');render()}else alert('Invalid email or password.')}
const nav=[['dashboard','Overview','Dashboard'],['riders','Riders','Riders Directory'],['vehicles','Fleet','Vehicles'],['deliveries','Operations','Deliveries'],['maintenance','Fleet','Maintenance'],['inspections','Fleet','Inspections'],['fuel','Fleet','Fuel & Mileage'],['incidents','Operations','Incidents'],['training','Riders','Training'],['documents','Data','Document Center'],['reports','Data','Reports'],['analytics','Management','Analytics'],['alerts','Management','Alert Center'],['settings','Administration','Settings'],['audit','Administration','Audit Log']];
function shell(){let groups={};nav.forEach(n=>(groups[n[1]]??=[]).push(n));return `<div class="shell"><aside class="sidebar"><div class="logo">ROAD HERO</div><div class="muted">Delivery Services</div><nav class="nav">${Object.entries(groups).map(([g,items])=>`<div class="nav-group"><small>${g}</small>${items.map(n=>`<button class="${page===n[0]?'active':''}" onclick="go('${n[0]}')">${n[2]}</button>`).join('')}</div>`).join('')}</nav><div style="margin-top:auto"><button class="navbtn" onclick="logout()">Logout</button></div></aside><section class="main"><header class="top"><div><div class="muted">Road Hero / ${esc(page)}</div><h1>${nav.find(n=>n[0]===page)?.[2]||'Dashboard'}</h1></div><div><button onclick="go('alerts')">🔔 ${data.alerts.length}</button> <b>Admin</b></div></header><div id="content"></div></section></div>`}
function renderPage(){const c=document.getElementById('content');if(page==='dashboard')c.innerHTML=dashboard();else if(page==='riders')c.innerHTML=riders();else if(page==='vehicles')c.innerHTML=vehicles();else if(page==='deliveries')c.innerHTML=generic('Deliveries','Delivery records and operational status.');else if(page==='maintenance')c.innerHTML=generic('Maintenance','Schedule and track vehicle maintenance.');else if(page==='inspections')c.innerHTML=generic('Inspections','Vehicle inspection checklist and history.');else if(page==='fuel')c.innerHTML=generic('Fuel & Mileage','Fuel costs, mileage and efficiency.');else if(page==='incidents')c.innerHTML=generic('Incidents','Track operational incidents and severity.');else if(page==='training')c.innerHTML=generic('Training','Track rider courses and certificates.');else if(page==='documents')c.innerHTML=generic('Document Center','Central compliance document management.');else if(page==='reports')c.innerHTML=generic('Reports','Reports generated from stored operational data.');else if(page==='analytics')c.innerHTML=analytics();else if(page==='alerts')c.innerHTML=generic('Alert Center','Compliance, maintenance and operational alerts.');else if(page==='settings')c.innerHTML=settings();else c.innerHTML=generic('Audit Log','Local activity history.');}
function dashboard(){const x=calc();return `<div class="grid"><div class="card"><div class="muted">Total Riders</div><div class="kpi">${x.riders}</div></div><div class="card"><div class="muted">Fleet Vehicles</div><div class="kpi">${x.vehicles}</div></div><div class="card"><div class="muted">Deliveries</div><div class="kpi">${x.deliveries}</div></div><div class="card"><div class="muted">Success Rate</div><div class="kpi">${x.success}%</div></div></div><div class="card" style="margin-top:18px"><h2>Requires Attention</h2><p>Expired documents: ${data.documents.filter(d=>d.status==='Expired').length}</p><p>Maintenance records: ${data.maintenance.length}</p><p>Open incidents: ${data.incidents.length}</p></div>`}
function riders(){return `<div class="card"><div class="top"><div><h2>Riders Directory</h2><p class="muted">Manage rider profiles, assignments and performance.</p></div><button class="primary" style="width:auto" onclick="addRider()">+ Add Rider</button></div><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Rider</th><th>Vehicle</th><th>Team</th><th>Deliveries</th><th>Success</th><th>Attendance</th><th>KPI</th><th>Status</th><th>Actions</th></tr></thead><tbody>${data.riders.map(r=>`<tr><td>${esc(r.id)}</td><td><b>${esc(r.name)}</b></td><td>${esc(r.vehicle||'Unassigned')}</td><td>${esc(r.team)}</td><td>${r.deliveries}</td><td>${r.success}%</td><td>${r.attendance}%</td><td>${r.kpi}%</td><td><span class="badge">${esc(r.status)}</span></td><td class="actions"><button onclick="editRider('${r.id}')">Edit</button><button class="danger" onclick="deleteRider('${r.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`}
function addRider(){editing=null;modal('Add Rider',{id:'R-'+String(data.riders.length+1).padStart(3,'0'),name:'',vehicle:'',team:'',deliveries:0,success:0,attendance:0,kpi:0,status:'Active'})}
function editRider(id){editing=id;modal('Edit Rider',data.riders.find(r=>r.id===id))}
function modal(title,r){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><form class="modal" onsubmit="saveRider(event)"><h2>${title}</h2><label class="field">Rider ID<input id="f_id" required value="${esc(r.id)}"></label><label class="field">Name<input id="f_name" required value="${esc(r.name)}"></label><label class="field">Vehicle<input id="f_vehicle" value="${esc(r.vehicle||'')}"></label><label class="field">Team<input id="f_team" value="${esc(r.team||'')}"></label><label class="field">Deliveries<input id="f_deliveries" type="number" value="${r.deliveries||0}"></label><label class="field">Success %<input id="f_success" type="number" min="0" max="100" value="${r.success||0}"></label><label class="field">Attendance %<input id="f_attendance" type="number" min="0" max="100" value="${r.attendance||0}"></label><label class="field">KPI %<input id="f_kpi" type="number" min="0" max="100" value="${r.kpi||0}"></label><label class="field">Status<select id="f_status"><option>Active</option><option>On Leave</option><option>Offboarded</option></select></label><button class="primary" type="submit">Save Rider</button><button type="button" onclick="document.getElementById('modal').remove()">Cancel</button></form></div>`);f_status.value=r.status||'Active'}
function saveRider(e){e.preventDefault();const r={id:f_id.value,name:f_name.value,vehicle:f_vehicle.value,team:f_team.value,deliveries:+f_deliveries.value,success:+f_success.value,attendance:+f_attendance.value,kpi:+f_kpi.value,status:f_status.value};if(editing){const i=data.riders.findIndex(x=>x.id===editing);data.riders[i]=r}else data.riders.push(r);save();document.getElementById('modal').remove();render()}
function deleteRider(id){if(confirm('Delete this rider? This removes the active rider record locally.')){data.riders=data.riders.filter(r=>r.id!==id);save();render()}}
function vehicles(){return `<div class="card"><div class="top"><h2>Vehicles</h2><button onclick="addVehicle()">+ Add Vehicle</button></div><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Vehicle</th><th>Registration</th><th>Status</th><th>Mileage</th></tr></thead><tbody>${data.vehicles.map(v=>`<tr><td>${esc(v.id)}</td><td>${esc(v.name)}</td><td>${esc(v.registration)}</td><td><span class="badge">${esc(v.status)}</span></td><td>${v.mileage.toLocaleString()} km</td></tr>`).join('')}</tbody></table></div></div>`}
function addVehicle(){const n=prompt('Vehicle name');if(!n)return;data.vehicles.push({id:'V-'+String(data.vehicles.length+1).padStart(3,'0'),name:n,registration:'',status:'Active',mileage:0});save();render()}
function generic(t,d){return `<div class="card"><h2>${t}</h2><p class="muted">${d}</p><div class="grid"><div class="card"><div class="muted">Records</div><div class="kpi">${({deliveries:data.deliveries,maintenance:data.maintenance,inspections:data.inspections,fuel:data.fuel,incidents:data.incidents,training:data.training,documents:data.documents,alerts:data.alerts}[page]||[]).length}</div></div></div></div>`}
function analytics(){const x=calc();return `<div class="grid"><div class="card"><div class="muted">Fleet Utilization</div><div class="kpi">${x.vehicles?Math.round(x.active/x.vehicles*100):0}%</div></div><div class="card"><div class="muted">Delivery Performance</div><div class="kpi">${x.success}%</div></div><div class="card"><div class="muted">Rider Performance</div><div class="kpi">${x.riders?Math.round(data.riders.reduce((a,r)=>a+r.kpi,0)/x.riders):0}%</div></div><div class="card"><div class="muted">Open Incidents</div><div class="kpi">${data.incidents.length}</div></div></div>`}
function settings(){return `<div class="card"><h2>Settings</h2><p>Local organization, branding, navigation, KPI and data controls.</p><button onclick="backup()">Export JSON Backup</button> <button onclick="resetData()">Reset Demo Data</button><hr><p class="muted">Authentication is local to this device. No cloud database is used.</p></div>`}
function backup(){const a=document.createElement('a');a.href='data:application/json,'+encodeURIComponent(JSON.stringify(data));a.download='road-hero-backup.json';a.click()}
function resetData(){if(confirm('Reset all local data to demo data?')){data=JSON.parse(JSON.stringify(seed));save();render()}}
function go(p){page=p;render()}function logout(){sessionStorage.removeItem('rhAuth');page='login';render()}
if(sessionStorage.getItem('rhAuth')==='1')render();else{page='login';render()}