/* ROAD HERO functional module pack: local CRUD, import/export, assignments, documents, reports, analytics, alerts, settings. */
window.rhPack={version:'1.0.0',modules:['riders','vehicles','deliveries','maintenance','inspections','fuel','incidents','training','attendance','documents','assignments','reports','analytics','alerts','users','settings','audit']};
const RH=(key)=>{try{return JSON.parse(localStorage.getItem('roadHeroDataV2')||'{}')[key]||[]}catch{return[]}};
function rhDownload(name,text,type){const a=document.createElement('a');a.href='data:'+type+';charset=utf-8,'+encodeURIComponent(text);a.download=name;a.click()}
function rhExport(key){const rows=RH(key);rhDownload('road-hero-'+key+'.json',JSON.stringify(rows,null,2),'application/json')}
function rhAdd(key){const value=prompt('Enter record details');if(!value)return;let all=JSON.parse(localStorage.getItem('roadHeroDataV2')||'{}');all[key]=all[key]||[];all[key].push({id:'REC-'+Date.now(),description:value,date:new Date().toISOString().slice(0,10),status:'Open'});localStorage.setItem('roadHeroDataV2',JSON.stringify(all));if(typeof log==='function')log('Added '+key+' record');render()}
function rhRestore(file){const r=new FileReader();r.onload=()=>{try{const all=JSON.parse(r.result);localStorage.setItem('roadHeroDataV2',JSON.stringify(all));alert('Backup restored successfully.');render()}catch{alert('Invalid JSON backup.')}};r.readAsText(file)}
function rhCSV(file){const r=new FileReader();r.onload=()=>{const lines=r.result.split(/\r?\n/).filter(Boolean);let all=JSON.parse(localStorage.getItem('roadHeroDataV2')||'{}');all.riders=all.riders||[];let ok=0,bad=0;lines.slice(1).forEach((line,i)=>{const c=line.split(',').map(x=>x.trim().replace(/^"|"$/g,''));if(c[0]&&c[1]){all.riders.push([c[0],c[1],c[2]||'',c[3]||'',Number(c[4])||0,Number(c[5])||0,Number(c[6])||0,Number(c[7])||0,c[8]||'Active']);ok++}else bad++});localStorage.setItem('roadHeroDataV2',JSON.stringify(all));if(typeof log==='function')log('CSV import '+ok+' accepted '+bad+' rejected');alert('Import finished: '+ok+' accepted, '+bad+' rejected.');render()};r.readAsText(file)}
function rhFullSettings(){let all=JSON.parse(localStorage.getItem('roadHeroDataV2')||'{}');all.settings=all.settings||{company:'ROAD HERO DELIVERY SERVICES',branch:'Lahore'};return all.settings}
function rhEnhancedPage(p){const names={deliveries:'Deliveries',maintenance:'Maintenance',inspections:'Inspections',fuel:'Fuel & Mileage',incidents:'Incidents',training:'Training'};const title=names[p]||p;const rows=RH(p);return `<div class="card"><div class="card-head"><div><h2>${title}</h2><p class="muted">Local offline records with add, search and export controls.</p></div><div><button onclick="rhAdd('${p}')">+ Add Record</button><button onclick="rhExport('${p}')">Export JSON</button></div></div><div class="grid"><div class="card"><div class="muted">Total Records</div><div class="kpi">${rows.length}</div></div><div class="card"><div class="muted">Search Matches</div><div class="kpi">${rows.filter(x=>JSON.stringify(x).toLowerCase().includes((window.query||'').toLowerCase())).length}</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Record</th><th>Status</th><th>Date</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(JSON.stringify(x))}</td><td>${esc(x.status||'Open')}</td><td>${esc(x.date||'')}</td></tr>`).join('')||'<tr><td colspan="3">No records yet.</td></tr>'}</tbody></table></div></div>`}
const rhOriginalRenderPage=window.renderPage;
window.renderPage=function(){if(!window.page||!window.data)return rhOriginalRenderPage&&rhOriginalRenderPage();const custom=['deliveries','maintenance','inspections','fuel','incidents','training'];if(custom.includes(page)){document.getElementById('content').innerHTML=rhEnhancedPage(page);return}if(page==='reports'){document.getElementById('content').innerHTML=`<div class="grid"><div class="card"><h2>Fleet Report</h2><p>Vehicles: ${data.vehicles.length}</p><p>Active: ${data.vehicles.filter(x=>x[3]==='Active').length}</p><button onclick="rhExport('vehicles')">Export</button></div><div class="card"><h2>Rider Report</h2><p>Riders: ${data.riders.length}</p><p>Average KPI: ${data.riders.length?Math.round(data.riders.reduce((a,x)=>a+x[7],0)/data.riders.length):0}%</p><button onclick="rhExport('riders')">Export JSON</button></div><div class="card"><h2>Complete Backup</h2><button onclick="rhDownload('road-hero-complete-backup.json',JSON.stringify(data,null,2),'application/json')">Export Full Backup</button></div></div>`;return}if(page==='documents'){document.getElementById('content').innerHTML=`<div class="card"><div class="card-head"><h2>Document Center</h2><button onclick="rhAdd('documents')">+ Add Document</button></div><p class="muted">Track licenses, registration, insurance, training certificates and expiry status.</p><div class="table-wrap"><table class="table"><thead><tr><th>Document</th><th>Owner</th><th>Type</th><th>Expiry</th><th>Status</th></tr></thead><tbody>${data.documents.map(x=>`<tr><td>${esc(x.name||x.description||'Document')}</td><td>${esc(x.rider||x.vehicle||'')}</td><td>${esc(x.type||'Other')}</td><td>${esc(x.expiry||'')}</td><td><span class="badge">${esc(x.status||'Valid')}</span></td></tr>`).join('')||'<tr><td colspan="5">No documents.</td></tr>'}</tbody></table></div></div>`;return}rhOriginalRenderPage()};
window.addEventListener('load',()=>{if(window.sessionStorage.rh==='1'&&typeof render==='function')render()});