const KEY='rh_final_v1';
const AUTH_USER='admin'; const AUTH_PASS='roadhero';
const seed={riders:[
{id:'RD-0042',name:'Ahmed Khan',vehicle:'VH-0012',team:'Team Alpha',deliveries:1482,success:97.2,kpi:94,attendance:98,status:'Active',compliance:'Compliant',hub:'North Station',joined:'Oct 12, 2021'},
{id:'RD-0108',name:'Sarah Jenkins',vehicle:'VH-0455',team:'Team Bravo',deliveries:945,success:92.4,kpi:82,attendance:96,status:'Active',compliance:'Compliant',hub:'East Station',joined:'Mar 18, 2022'},
{id:'RD-0221',name:'Marcus Torres',vehicle:'VH-0199',team:'Team Alpha',deliveries:412,success:81.5,kpi:68,attendance:91,status:'Active',compliance:'Pending Review',hub:'Central Hub',joined:'Jun 04, 2022'},
{id:'RD-0305',name:'David Chen',vehicle:'VH-0882',team:'Team Charlie',deliveries:288,success:65.3,kpi:54,attendance:88,status:'Suspended',compliance:'Non-Compliant',hub:'North Station',joined:'Oct 01, 2022'},
{id:'RD-0410',name:'Usman Ali',vehicle:'Unassigned',team:'Team Bravo',deliveries:176,success:88.1,kpi:79,attendance:94,status:'Active',compliance:'Compliant',hub:'Lahore',joined:'Jan 15, 2023'}],
vehicles:[{id:'VH-0012',reg:'ABC-123',name:'Toyota Corolla 2022',rider:'Ahmed Khan',branch:'Lahore',odo:42680,compliance:'Compliant',status:'Active'}, {id:'VH-0455',reg:'XYZ-987',name:'Honda City 2021',rider:'Usman Ali',branch:'Karachi',odo:65120,compliance:'Service Due',status:'Active'}, {id:'VH-0199',reg:'LMN-456',name:'Suzuki Bolan 2019',rider:'Unassigned',branch:'Islamabad',odo:112400,compliance:'Non-Compliant',status:'Maintenance'}],
deliveries:[],maintenance:[],inspections:[],fuel:[],incidents:[],training:[],attendance:[],documents:[{name:"Driver's License",owner:'Ahmed Khan',type:'License',expiry:'Jan 15, 2027',status:'Valid'},{name:'Safety Training',owner:'Ahmed Khan',type:'Training',expiry:'Nov 02, 2024',status:'Valid'},{name:'Background Check',owner:'Ahmed Khan',type:'Background',expiry:'Aug 10, 2023',status:'Expired'}],alerts:[{title:'Critical: Requires Attention',text:'7 expired documents blocking dispatch.',kind:'critical'},{title:'Warning',text:'4 documents expiring soon.',kind:'warning'}],audit:[],settings:{company:'ROAD HERO DELIVERY SERVICES',branch:'Lahore'}};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed; let page='dashboard', search='';
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function log(action){db.audit.unshift({date:new Date().toLocaleString(),user:'Admin',action});save()}
function app(){if(sessionStorage.rh!=='1'){document.querySelector('#app').innerHTML=login();return}document.querySelector('#app').innerHTML=layout();content()}
function login(){return `<div class="login-page"><div class="login-card"><div class="brand-mark">▣</div><div class="brand-name">Road Hero</div><div class="brand-sub">Fleet Management Portal</div><form onsubmit="signin(event)"><label>Employee ID or Email<input id="loginUser" type="text" placeholder="Enter your ID or Email" autocomplete="off" required></label><label>Password<input id="loginPass" type="password" placeholder="Password" autocomplete="off" required></label><label class="remember"><input type="checkbox"> Remember me on this device</label><button class="primary full">Secure Login</button></form><div class="auth-note">◉ Authorized Personnel Only</div></div></div>`}
function signin(e){e.preventDefault();if(loginUser.value===AUTH_USER&&loginPass.value===AUTH_PASS){sessionStorage.rh='1';log('Signed in');app()}else alert('Invalid credentials')}
const nav=[['Overview','Dashboard','▦'],['Fleet','Fleet Status','▣'],['Fleet','Routes','⌁'],['Fleet','Maintenance','⚒'],['Fleet','Compliance','✓'],['Riders','Riders','♙'],['Operations','Deliveries','▤'],['Operations','Incidents','!'],['Data','Documents','□'],['Data','Excel Import','⇧'],['Management','Analytics','▥'],['Management','Alerts','△'],['Administration','Users & Roles','♙'],['Administration','Settings','⚙']];
function layout(){let groups={};nav.forEach(n=>(groups[n[0]]??=[]).push(n));return `<div class="app-shell"><aside class="sidebar"><div class="side-brand"><span>▣</span><div><b>Road Hero</b><small>Fleet Management</small></div></div><button class="new-btn" onclick="quick('deliveries')">＋ New Delivery</button><nav>${Object.entries(groups).map(([g,items])=>`<section><small>${g}</small>${items.map(n=>`<button class="side-item ${page===key(n[1])?'active':''}" onclick="go('${key(n[1])}')"><i>${n[2]}</i>${n[1]}</button>`).join('')}</section>`).join('')}</nav><div class="side-bottom"><button onclick="go('settings')">⚙ Settings</button><button onclick="alert('Support is available from your administrator.')">? Support</button><button onclick="logout()">⇥ Logout</button></div></aside><main class="main"><header class="topbar"><div class="crumb">${page==='dashboard'?'Dashboard':'Fleet › '+title()}</div><div class="top-actions"><input class="search" placeholder="Search..." value="${esc(search)}" oninput="search=this.value;content()"><button onclick="go('alerts')">♧</button><button onclick="alert('No new notifications')">◔</button><span class="avatar">A</span></div></header><div id="content"></div></main></div>`}
function key(x){return ({'Dashboard':'dashboard','Fleet Status':'vehicles','Routes':'deliveries','Maintenance':'maintenance','Compliance':'compliance','Riders':'riders','Deliveries':'deliveries','Incidents':'incidents','Documents':'documents','Excel Import':'import','Analytics':'analytics','Alerts':'alerts','Users & Roles':'users','Settings':'settings'})[x]||x.toLowerCase()}
function go(p){page=p;search='';app()}
function logout(){log('Signed out');sessionStorage.removeItem('rh');app()}
function title(){return ({riders:'Riders',vehicles:'Fleet Status',deliveries:'Deliveries',maintenance:'Maintenance',inspections:'Inspections',fuel:'Fuel & Mileage',incidents:'Incidents',training:'Training',documents:'Documents',import:'Excel Performance Import',analytics:'Analytics',alerts:'Alerts',users:'Users & Roles',settings:'Settings',compliance:'Compliance'})[page]||'Dashboard'}
function content(){const c=document.querySelector('#content');if(page==='dashboard')c.innerHTML=dashboard();else if(page==='riders')c.innerHTML=riders();else if(page==='vehicles')c.innerHTML=vehicles();else if(page==='compliance')c.innerHTML=compliance();else if(page==='analytics')c.innerHTML=analytics();else if(page==='alerts')c.innerHTML=alerts();else if(page==='documents')c.innerHTML=documents();else if(page==='import')c.innerHTML=imports();else if(page==='settings')c.innerHTML=settings();else if(page==='users')c.innerHTML=users();else if(page==='reports')c.innerHTML=reports();else c.innerHTML=modulePage(page)}
function head(h,sub,actions=''){return `<div class="page-head"><div><h1>${h}</h1><p>${sub}</p></div><div class="head-actions">${actions}</div></div>`}
function dashboard(){let v=db.vehicles,r=db.riders;return head('Fleet Operations Dashboard','Real-time overview of fleet, riders, compliance and operational performance.','<select><option>Today</option><option>Last 7 days</option><option>Last 30 days</option></select><button>All Branches⌄</button><button class="primary small" onclick="alert(\'Report exported\')">Export Report</button>')+`<div class="quick-row"><button onclick="quick('vehicles')">＋ Add Vehicle</button><button onclick="addRider()">＋ Add Rider</button><button onclick="quick('assignments')">＋ Assign Vehicle</button><button onclick="go('import')">⇧ Upload Excel</button><button onclick="quick('inspections')">▣ Record Inspection</button><button onclick="quick('maintenance')">⚒ Add Maintenance</button><button class="danger-btn" onclick="quick('incidents')">⚠ Report Issue</button></div><div class="alert-strip"><div class="critical"><b>◉ Critical: Requires Attention</b><span>7 expired documents blocking dispatch.</span></div><div class="warning"><b>△ Warning</b><span>4 documents expiring soon, 8 vehicles approaching scheduled service.</span></div></div><div class="kpi-grid">${[['TOTAL VEHICLES',v.length,'+ 4'],['ACTIVE VEHICLES',v.filter(x=>x.status==='Active').length,'87.5%'],['ACTIVE RIDERS',r.filter(x=>x.status==='Active').length,'139 operational'],['FLEET COMPLIANCE','94.8%','Green'],['TODAY’S DELIVERIES','2,846',''],['SUCCESS RATE','94.2%',''],['AVG RIDER SCORE','82.6',''],['VEHICLES IN MAINT.','9','']].map(x=>`<div class="kpi-card"><small>${x[0]}</small><strong>${x[1]}</strong><em>${x[2]}</em></div>`).join('')}</div><div class="dashboard-grid"><div class="panel"><div class="panel-title"><b>Delivery Performance</b><span>● Planned　● Completed　● Failed</span></div><div class="bars">${[58,72,66,55,86,48,78].map((n,i)=>`<div><span style="height:${n}px"></span><small>${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</small></div>`).join('')}</div></div><div class="panel"><div class="panel-title"><b>Fleet Status</b><span>128 Total</span></div><div class="donut"><div><strong>128</strong><small>Total</small></div></div><div class="legend"><span>■ Active 84%</span><span>■ Maint. 11%</span><span>■ Other 5%</span></div></div></div><div class="panel table-panel"><div class="panel-title"><b>Top Rider Performance</b><a onclick="go('riders')">View All</a></div>${ridersTable(db.riders.slice(0,4),false)}</div>`}
function riders(){let rows=db.riders.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));return head('Rider Management','Manage rider profiles, performance, compliance and assignments.','<button onclick="downloadRiders()">⇩ Export</button><button onclick="go(\'import\')">⇧ Import</button><button class="primary" onclick="addRider()">＋ Add Rider</button>')+`<div class="filters"><b>☷ Filters:</b><select><option>Status: All</option><option>Active</option><option>Suspended</option></select><select><option>Branch: All</option><option>Lahore</option></select><select><option>Team: All</option><option>Team Alpha</option></select><select><option>KPI: All</option><option>Excellent</option></select><a onclick="search='';content()">Clear Filters</a></div><div class="panel table-panel">${ridersTable(rows,true)}</div>`}
function ridersTable(rows,actions){return `<div class="table-meta">${rows.length?`Showing 1 to ${rows.length} of 142 riders`:''}<span>25 / page　‹　<b>1</b>　2　3　…　15　›</span></div><div class="table-wrap"><table><thead><tr><th>□</th><th>Rider ID</th><th>Rider Name</th><th>Vehicle</th><th>Team</th><th>Deliveries</th><th>Success Rate</th><th>KPI Score</th><th>Compliance</th><th>Status</th>${actions?'<th>Actions</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr><td>□</td><td>${r.id}</td><td><b class="link" onclick="profile('${r.id}')">${esc(r.name)}</b></td><td>${r.vehicle}</td><td>${r.team}</td><td>${r.deliveries.toLocaleString()}</td><td>${r.success}%</td><td><span class="kpi-pill ${r.kpi<70?'bad':r.kpi<85?'warn':''}">${r.kpi} ${r.kpi>=90?'Excellent':r.kpi>=80?'Very Good':r.kpi>=60?'Needs Impr.':'Critical'}</span></td><td><span class="status ${r.compliance==='Compliant'?'ok':r.compliance==='Non-Compliant'?'bad':'warn'}">${r.compliance}</span></td><td><span class="status">${r.status}</span></td>${actions?`<td class="action-cell"><button onclick="editRider('${r.id}')">Edit</button><button class="danger-text" onclick="deleteRider('${r.id}')">Delete</button></td>`:''}</tr>`).join('')}</tbody></table></div>`}
function addRider(){modal('Add Rider',riderForm(),saveRider)}
function editRider(id){let r=db.riders.find(x=>x.id===id);modal('Edit Rider',riderForm(r),()=>saveRider(id))}
function riderForm(r={}){return `<div class="form-grid"><label>Rider ID<input id="f_id" value="${r.id||'RD-'+String(Date.now()).slice(-4)}"></label><label>Rider Name<input id="f_name" value="${esc(r.name||'')}" required></label><label>Vehicle<input id="f_vehicle" value="${esc(r.vehicle||'')}"></label><label>Team<select id="f_team"><option>${r.team||'Team Alpha'}</option><option>Team Bravo</option><option>Team Charlie</option></select></label><label>Deliveries<input id="f_del" type="number" value="${r.deliveries||0}"></label><label>Success Rate<input id="f_success" type="number" step="0.1" value="${r.success||0}"></label><label>KPI Score<input id="f_kpi" type="number" value="${r.kpi||0}"></label><label>Status<select id="f_status"><option>Active</option><option>On Leave</option><option>Suspended</option><option>Offboarded</option></select></label></div>`}
function saveRider(id){let x={id:f_id.value,name:f_name.value,vehicle:f_vehicle.value,team:f_team.value,deliveries:+f_del.value,success:+f_success.value,kpi:+f_kpi.value,attendance:94,status:f_status.value,compliance:'Compliant',hub:'Lahore',joined:new Date().toLocaleDateString()};let i=db.riders.findIndex(r=>r.id===(id||x.id));if(i<0)db.riders.push(x);else db.riders[i]=x;save();log((id?'Edited':'Added')+' rider '+x.id);closeModal();app()}
function deleteRider(id){if(confirm('Delete this rider?')){db.riders=db.riders.filter(r=>r.id!==id);save();log('Deleted rider '+id);app()}}
function profile(id){let r=db.riders.find(x=>x.id===id);document.querySelector('#content').innerHTML=`<div class="profile-head"><button onclick="go('riders')">← Riders</button><span>Fleet　›　Riders　›　${r.id}</span></div><div class="profile-card"><div class="rider-summary"><div class="photo">AK</div><div><h1>${r.name}</h1><span class="idtag">${r.id}</span> <span class="status ok">● ${r.status}</span><p>▣ Assigned Vehicle <b>${r.vehicle}</b></p><p>⌖ Current Hub <b>${r.hub}</b></p><p>▣ Joined <b>${r.joined}</b></p><button onclick="editRider('${r.id}')">✎ Edit Rider</button> <button class="danger-outline" onclick="offboard('${r.id}')">♙ Offboard</button></div></div><div class="metric-row">${[['Overall KPI',r.kpi,'Excellent'],['Deliveries',r.deliveries.toLocaleString(),'Lifetime Total'],['Success Rate',r.success+'%','Last 30 Days'],['Attendance',r.attendance+'%','YTD Punctuality']].map(x=>`<div><small>${x[0]}</small><strong>${x[1]}</strong><em>${x[2]}</em></div>`).join('')}</div></div><div class="tabs">${['Overview','Performance','Attendance','Compliance','Vehicle History','Deliveries','Incidents','Training','Documents','Notes'].map((x,i)=>`<button class="${x==='Documents'?'selected':''}" onclick="profileTab('${r.id}','${x}')">${x}</button>`).join('')}</div><div id="profileBody">${profileDocs(r)}</div>`}
function profileTab(id,t){let r=db.riders.find(x=>x.id===id);document.querySelector('#profileBody').innerHTML=t==='Documents'?profileDocs(r):`<div class="panel"><h2>${t}</h2><p>Manage ${t.toLowerCase()} for ${esc(r.name)}. Records are saved locally and remain available offline.</p><button onclick="quick('${t.toLowerCase()}')">＋ Add ${t} Record</button></div>`}
function profileDocs(r){return `<div class="section-head"><div><h2>Rider Documents</h2><p>Manage required compliance and identification documents.</p></div><button class="primary" onclick="quick('documents')">⇧ Upload New</button></div><div class="doc-grid">${db.documents.map(d=>`<div class="doc-card ${d.status==='Expired'?'expired':''}"><span class="status ${d.status==='Expired'?'bad':'ok'}">${d.status}</span><div class="doc-icon">▧</div><h3>${esc(d.name)}</h3><p>ID: DL-992384-XX</p><div>Issued: <b>Jan 15, 2022</b></div><div>Expires: <b>${d.expiry}</b></div><button onclick="alert('Document preview')">View</button> <button onclick="quick('documents')">Edit</button></div>`).join('')}</div>`}
function offboard(id){let r=db.riders.find(x=>x.id===id);modal('Offboarding Workflow',`<div class="off-alert">⚠ Action Required: Outstanding Equipment<br><small>Rider currently has company-issued items that must be returned before finalization.</small></div><div class="checklist"><label>□ Physical Inspection Complete</label><label>□ Keys Returned</label><label>□ Delivery Bag Returned</label><label>□ Safety Vest & ID surrendered</label><label>□ Terminal returned</label></div><p>Overall Progress　2/6</p>`,()=>{r.status='Offboarded';save();log('Offboarded '+id);closeModal();app()})}
function vehicles(){return head('Fleet Vehicles','Manage and monitor all active vehicles in the network.','<button>⇧ Import Excel</button><button>⇩ Export</button><button class="primary" onclick="quick(\'vehicles\')">＋ Add Vehicle</button>')+`<div class="filters"><b>STATUS</b><select><option>All Statuses</option></select><select><option>All Types</option></select><select><option>All Branches</option></select><select><option>All Compliance</option></select><input placeholder="Search rider..."></div><div class="panel table-panel">${vehicleTable()}</div>`}
function vehicleTable(){return `<div class="table-wrap"><table><thead><tr><th>□</th><th>Vehicle ID</th><th>Registration</th><th>Vehicle</th><th>Rider</th><th>Branch</th><th>Odometer</th><th>Compliance</th></tr></thead><tbody>${db.vehicles.map(v=>`<tr onclick="vehicleProfile('${v.id}')"><td>□</td><td>${v.id}</td><td>${v.reg}</td><td><b>${v.name}</b></td><td>${v.rider}</td><td>${v.branch}</td><td>${v.odo.toLocaleString()} KM</td><td><span class="status ${v.compliance==='Compliant'?'ok':v.compliance==='Non-Compliant'?'bad':'warn'}">● ${v.compliance}</span></td></tr>`).join('')}</tbody></table></div>`}
function vehicleProfile(id){let v=db.vehicles.find(x=>x.id===id);document.querySelector('#content').innerHTML=`<div class="profile-card vehicle-profile"><div><span class="idtag">${v.id}　● ${v.status}</span><h1>${v.name}</h1><p>⌖ Registration: ${v.reg}</p></div><div><button onclick="quick('vehicles')">✎ Edit Vehicle</button><button onclick="quick('assignments')">♙ Assign Rider</button><button class="danger-outline" onclick="quick('incidents')">⚠ Report Issue</button></div></div><div class="metric-row">${[['Current Rider',v.rider,''],['Current Odometer',v.odo.toLocaleString()+' KM',''],['Fleet Utilization','91%',''],['Overall Compliance','98%','']].map(x=>`<div><small>${x[0]}</small><strong>${x[1]}</strong><em>${x[2]}</em></div>`).join('')}</div><div class="vehicle-body"><div class="panel"><h2>Technical Information</h2><div class="detail-grid"><p>VIN<br><b>JTDB3CA50234567</b></p><p>ENGINE NO<br><b>2ZR-FE9876543</b></p><p>MAKE / MODEL<br><b>Toyota / Corolla LE</b></p><p>FUEL TYPE<br><b>Petrol (Unleaded)</b></p><p>PURCHASE DATE<br><b>12 Oct 2021</b></p><p>ASSET VALUE<br><b>$22,500 USD</b></p></div><div class="car-photo">Toyota Corolla 2022</div></div><div class="panel"><h2>REAL-TIME STATS</h2><p>Last inspection　02 Nov 2023</p><p>Next Service　14 Days</p><h3>Compliance Documents</h3>${['Vehicle Insurance','Road Tax','Fitness Permit','Visa','Work Permit','RTA Permit'].map((x,i)=>`<div class="mini-doc">▧ ${x}<span class="status ${i===1||i===5?'warn':'ok'}">${i===1||i===5?'Expiring':'Valid'}</span></div>`).join('')}</div></div>`}
function compliance(){return head('Compliance','Monitor rider and vehicle compliance status.','<button class="primary" onclick="quick(\'documents\')">＋ Add Document</button>')+`<div class="kpi-grid small-grid">${[['COMPLIANT','116'],['EXPIRING SOON','7'],['EXPIRED','5'],['MISSING','2']].map(x=>`<div class="kpi-card"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</div><div class="panel">${db.riders.map(r=>`<div class="compliance-row"><b>${r.name}</b><span>${r.id}</span><span class="status ${r.compliance==='Compliant'?'ok':r.compliance==='Non-Compliant'?'bad':'warn'}">${r.compliance}</span><button onclick="profile('${r.id}')">View</button></div>`).join('')}</div>`}
function modulePage(p){let names={deliveries:'Deliveries',maintenance:'Maintenance',inspections:'Inspections',fuel:'Fuel & Mileage',incidents:'Incidents',training:'Training'};let h=names[p]||title();let arr=db[p]||[];return head(h,'Manage operational records with the same Road Hero workspace.','<button class="primary" onclick="quick(\''+p+'\')">＋ Add Record</button>')+`<div class="kpi-grid small-grid"><div class="kpi-card"><small>TOTAL RECORDS</small><strong>${arr.length}</strong></div><div class="kpi-card"><small>OPEN</small><strong>${arr.filter(x=>x.status!=='Completed').length}</strong></div><div class="kpi-card"><small>THIS PERIOD</small><strong>${arr.length}</strong></div></div><div class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Description</th><th>Status</th><th>Action</th></tr></thead><tbody>${arr.map(x=>`<tr><td>${x.date||''}</td><td>${esc(x.description||x.name||'Record')}</td><td><span class="status">${esc(x.status||'Open')}</span></td><td><button onclick="editRecord('${p}','${x.id}')">Edit</button><button class="danger-text" onclick="deleteRecord('${p}','${x.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="4">No records yet.</td></tr>'}</tbody></table></div></div>`}
function quick(p){if(p==='vehicles'){let name=prompt('Vehicle name');if(name){db.vehicles.push({id:'VH-'+String(Date.now()).slice(-4),reg:'',name,rider:'Unassigned',branch:'Lahore',odo:0,compliance:'Compliant',status:'Active'});save();log('Added vehicle');app()}return}let val=prompt('Enter record description');if(!val)return;db[p]=db[p]||[];db[p].push({id:'REC-'+Date.now(),description:val,date:new Date().toLocaleDateString(),status:'Open'});save();log('Added '+p);app()}
function editRecord(p,id){let x=db[p].find(a=>a.id===id);let v=prompt('Edit description',x.description);if(v){x.description=v;save();log('Edited '+p);app()}}
function deleteRecord(p,id){if(confirm('Delete record?')){db[p]=db[p].filter(x=>x.id!==id);save();log('Deleted '+p);app()}}
function documents(){return head('Rider Documents','Manage required compliance and identification documents.','<button class="primary" onclick="quick(\'documents\')">⇧ Upload New</button>')+`<div class="doc-grid">${db.documents.map(d=>`<div class="doc-card ${d.status==='Expired'?'expired':''}"><span class="status ${d.status==='Expired'?'bad':'ok'}">${d.status}</span><div class="doc-icon">▧</div><h3>${d.name}</h3><p>${d.type}</p><p>Expires: <b>${d.expiry}</b></p><button>View</button><button onclick="quick('documents')">Edit</button><button class="danger-text" onclick="this.closest('.doc-card').remove()">Delete</button></div>`).join('')}</div>`}
function imports(){return head('Excel Performance Import','Update rider performance data from your Excel spreadsheet.','')+`<div class="import-layout"><div class="panel"><div class="steps"><b>1 Upload</b><b>2 Map Columns</b><b>3 Validate</b><b>4 Import</b></div><div class="dropzone"><div>⇧</div><h2>Drag & Drop Excel File</h2><p>or browse for files</p><input type="file" accept=".csv,.xlsx,.xls" onchange="importFile(event)"><small>Supported formats: .xlsx, .xls, .csv (Max 10MB)</small></div></div><div class="panel validation"><h2>Validation Summary</h2><div class="big-number">0</div><p>Total Rows</p><div class="v-row"><span>Valid</span><b>0</b></div><div class="v-row"><span>Warnings</span><b>0</b></div><div class="v-row"><span>Errors</span><b>0</b></div><div class="v-row"><span>Duplicates</span><b>0</b></div></div></div>`}
function importFile(e){let f=e.target.files[0];if(!f)return;let reader=new FileReader();reader.onload=()=>{let lines=String(reader.result).split(/\r?\n/).filter(Boolean);let count=Math.max(0,lines.length-1);alert('Validated '+count+' rows. CSV import is ready for review.');};reader.readAsText(f)}
function analytics(){return head('Analytics','Business intelligence overview across fleet and riders.','<select><option>Last 30 Days</option></select>')+`<div class="kpi-grid">${[['Fleet Utilization','91%'],['Rider Performance','82.6'],['Success Rate','94.2%'],['Compliance','94.8%']].map(x=>`<div class="kpi-card"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</div><div class="dashboard-grid"><div class="panel"><h2>Rider Performance</h2><div class="bars tall">${[94,82,68,54,79].map(n=>`<div><span style="height:${n*2}px"></span></div>`).join('')}</div></div><div class="panel"><h2>Vehicle Utilization</h2><div class="progress"><span style="width:91%"></span></div><p>91% utilized fleet</p></div></div>`}
function alerts(){return head('Alert Center','Critical warnings and operational notifications.','<button onclick="db.alerts=[];save();app()">Clear All</button>')+`<div class="alert-list">${db.alerts.map(a=>`<div class="alert-item ${a.kind}"><b>${a.title}</b><p>${a.text}</p><button onclick="this.parentElement.remove()">Mark Read</button></div>`).join('')||'<div class="panel">No active alerts.</div>'}</div>`}
function users(){return head('Users & Roles','Control local administrator access and roles.','<button class="primary" onclick="quick(\'users\')">＋ Add User</button>')+`<div class="panel"><div class="user-row"><b>Admin</b><span>Administrator</span><span>All permissions</span><button>Edit</button></div></div>`}
function settings(){return head('Settings','Configure organization and local application preferences.','')+`<div class="settings-grid">${['Organization','Branches','Depots','Teams','Shifts','Vehicle Types','Rider Statuses','Compliance Rules','KPI Weights','Notification Settings','Branding','Dashboard','Navigation','Custom Fields','Onboarding','Data & Backup','Security','Appearance'].map(x=>`<div class="panel setting"><h3>${x}</h3><p>Configure ${x.toLowerCase()}.</p><button onclick="alert('${x} settings saved locally')">Configure</button></div>`).join('')}</div>`}
function reports(){return head('Reports','Operational reports generated from stored local data.','<button onclick="downloadRiders()">Export</button>')+`<div class="settings-grid"><div class="panel"><h2>Fleet Report</h2><p>${db.vehicles.length} vehicles · ${db.riders.length} riders</p><button onclick="downloadRiders()">Export CSV</button></div><div class="panel"><h2>Compliance Report</h2><p>${db.documents.filter(x=>x.status==='Expired').length} expired documents</p></div></div>`}
function modal(h,body,submit){document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="modal"><div class="modal"><div class="modal-head"><h2>${h}</h2><button onclick="closeModal()">×</button></div><div>${body}</div><div class="modal-actions"><button onclick="closeModal()">Cancel</button><button class="primary" onclick="window.modalSubmit&&window.modalSubmit()">Save Changes</button></div></div></div>`);window.modalSubmit=submit}
function closeModal(){document.getElementById('modal')?.remove();window.modalSubmit=null}
function downloadRiders(){let csv='Rider ID,Rider,Vehicle,Team,Deliveries,Success,KPI,Status\n'+db.riders.map(r=>[r.id,r.name,r.vehicle,r.team,r.deliveries,r.success,r.kpi,r.status].join(',')).join('\n');let a=document.createElement('a');a.href='data:text/csv;charset=utf-8,'+encodeURIComponent(csv);a.download='road-hero-riders.csv';a.click()}
save();window.addEventListener('load',app);